### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by janskey** [garganshul108/Code-With-Mosh-Playlist-Downloader#28]
$ ./playlist_downloader.sh https://codewithmosh.com/courses/293204/lectures/4509750 NodeJS
scraping title page from https://codewithmosh.com/courses/293204/lectures/4509750
Traceback (most recent call last):
  File "scrape_via_login.py", line 37, in <module>
    main()
  File "scrape_via_login.py", line 18, in main
    authenticity_token = list(set(tree.xpath("//meta[@name='csrf-token']/@content")))[0]
IndexError: list index out of range
scraped into title.html
local scraping of contents
contents scraped
removing unneccesary title.html
NodeJS.txt
Traceback (most recent call last):
  File "scrape_list_via_login.py", line 54, in <module>
    main()
  File "scrape_list_via_login.py", line 20, in main
    authenticity_token = list(set(tree.xpath("//meta[@name='csrf-token']/@content")))[0]
IndexError: list index out of range

**Comment by paulatsydney** [comment]
Same error, mark to see if any solution

**Comment by shuboy2014** [comment]
@garganshul108 are you working on this issue ?

**Comment by shizlanski** [comment]
Any update on this one? I get the same error.

**Comment by Fighteros** [comment]
same problem they recaptcha and the script can't fetch csrf_token this can be fixed using selenuim to just fetch the csrf_token

**Comment by Art051** [comment]
Any

> same problem they recaptcha and the script can't fetch csrf_token this can be fixed using selenuim to just fetch the csrf_token

Do you know of any of the forks / clones to this project which actually work?

**Comment by spchaplin** [comment]
After spending several hours on this, getting the same error, I found a simpler way to do the downloads, which may be of help to others: https://www.rockyourcode.com/how-to-download-courses-from-teachable/ .  Before finding this solution, I attempted to follow the directions in the readme for this repositiory, but wasn't even able to install all the needed packages because of the deprecated python2 dependency.  I tried using python3 and installing all the dependencies for that.  I don't know if that was part of my problem that I was not using Python2 because the packages couldn't be found for it.

**Comment by manojdhadke** [comment]
My findings: The link**_(<link>/users/sign_in?clean_login=true&reset_purchase_session=1)_** led to a Cloudflare challenge page, typically displayed when a website employs Cloudflare's DDoS protection services. This challenge page mandates JavaScript execution and user interaction to gain access to the actual website content.

It necessitates an approach that is highly adaptable, encompassing the following strategies:

- Employing IP-rotating proxies.
- Utilizing residential proxies when dealing with challenging targets.
- Crafting comprehensive headers, including the User-Agent.
- Implementing Playwright to circumvent bot detection, especially when faced with JavaScript challenges, potentially incorporating the stealth module.
- Avoiding behaviours that could flag you as a bot.

The primary reason for the code failure at **_authenticity_token = list(set(tree.xpath("//meta[@name='csrf-token']/@content")))[0]_** is the absence of HTML containing the **_csrf-token_** due to the Cloudflare challenge page intervention.

Nevertheless, I achieved successful scraping by resorting to certain paid tools with free-tier access, such as zenrows.
